---

- name: ensure string- or array-based allowed accounts have been defined
  assert:
    that:
      - aws_account_match_allowed_account or aws_account_match_allowed_accounts
      - not (aws_account_match_allowed_account and aws_account_match_allowed_accounts)
    msg: Either only aws_account_match_allowed_account or only aws_account_match_allowed_accounts must be defined
  tags:
    # My own tag
    - aws_account_match
    # Special tag that will make it run regardless of what tag has been specified
    - always

- name: retrieve currently boto-logged in account number
  shell: "aws sts {% if aws_account_match_profile %}--profile {{ aws_account_match_profile }}{% endif %} get-caller-identity --output text --query 'Account'"
  args:
    executable: /bin/sh  
  check_mode: False
  changed_when: False
  register: _aws_account_match_number
  tags:
    # My own tag
    - aws_account_match
    # Special tag that will make it run regardless of what tag has been specified
    - always

- name: validate current login
  assert:
    that:
      - _aws_account_match_number is defined
      - _aws_account_match_number.stdout is defined
    msg: Could not retrieve account number. Make sure you are logged in to AWS.
  tags:
    # My own tag
    - aws_account_match
    # Special tag that will make it run regardless of what tag has been specified
    - always

- name: ensure current account matched single allowed account
  assert:
    that:
      - "_aws_account_match_number.stdout | string == aws_account_match_allowed_account | string"
    msg: "Currently logged in account ({{ _aws_account_match_number.stdout }}) does not match allowed account ({{ aws_account_match_allowed_account }})."
  when:
    - aws_account_match_allowed_account is defined
    - aws_account_match_allowed_account
  tags:
    # My own tag
    - aws_account_match
    # Special tag that will make it run regardless of what tag has been specified
    - always

- name: ensure current account matched any of all allowed accounts
  assert:
    that:
      - "_aws_account_match_number.stdout | string in aws_account_match_allowed_accounts | map('string') | list"
    msg: "Currently logged in account ({{ _aws_account_match_number.stdout }}) not in allowed accounts ({{ aws_account_match_allowed_accounts | join(', ') }})."
  when:
    - aws_account_match_allowed_accounts is defined
    - aws_account_match_allowed_accounts
  tags:
    # My own tag
    - aws_account_match
    # Special tag that will make it run regardless of what tag has been specified
    - always
